### ISSUE TITLE
make publish_dll is failing to run successfully

### ISSUE THREAD

**Issue by YOU54F** [pactflow/example-bi-directional-provider-dotnet#1]
Have installed .Net 3.1 and .Net 6.0, so it may be a PATH issue (3rd possible cause), but there also isn't a file in `src/example-bi-directional-provider-dotnet/bin/Debug/netcoreapp3.1/example-bi-directional-provider-dotnet.dl` which could be the 2nd possible cause.

```
dotnet src/example-bi-directional-provider-dotnet/bin/Debug/netcoreapp3.1/example-bi-directional-provider-dotnet.dll
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-src/example-bi-directional-provider-dotnet/bin/Debug/netcoreapp3.1/example-bi-directional-provider-dotnet.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
make: *** [publish_dll] Error 1
```

**Comment by Inksprout** [comment]
I've now fixed the incorrect publish_dll target. I've also added a global.json for this project, which should ensure the correct .net version is used when running the makefile commands. See commit here: https://github.com/pactflow/example-bi-directional-provider-dotnet/commit/f7cf881ad38f222115a24647d10e1800f99c62ff
